function printNodeInfo(node, title)
    disp(['[ ', title, ' ] id = ', num2str(node.node_id),...
      ' ; parent = ', num2str(node.parent_id),...
      ' ; coordinate = ( ', num2str(node.x), ', ', num2str(node.y),...
      ' ) ; cost = ',num2str(node.cost)]);
end